### ISSUE TITLE
Class 'Jose\Factory\JWKFactory' not found

### ISSUE THREAD

**Issue by tsdogs** [yiisoft/yii-auth-client#12]
I'm trying to use MS Graph AD authentication with OpenIdConnect

Using yii\authclient\OpenIdConnect raises this exception on authentication.
I tried adding it by: 
composer require spomky-labs/jose

but I get:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mdanter/ecc v0.5.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - mdanter/ecc v0.5.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - mdanter/ecc v0.5.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - spomky-labs/jose v7.1.0 requires mdanter/ecc 0.5.* -> satisfiable by mdanter/ecc[v0.5.0, v0.5.1, v0.5.2].
    - Installation request for spomky-labs/jose ^7.1 -> satisfiable by spomky-labs/jose[v7.1.0].

**Comment by tsdogs** [comment]
Installing php-gmp and enabling it solves the problem though I did not find documentation on the requirements.

**Comment by samdark** [comment]
@rustamwin is it still an issue?

**Comment by rustamwin** [comment]
This issue is out of date since we are using web-token framework.
