### ISSUE TITLE
Problem with sessions in PHP 7.2

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii-auth-client#6]
| Q                       | A
| ----------------------- | ---
| PHP version             | 7.2

Thanks to @FabrizioCaldarelli tests were fixed!
But for PHP 7.1 only. And not for 7.2 unfortunately.

Does anybody know what's the problem with sessions in 7.2?

```
session_set_cookie_params(): Cannot change session cookie parameters when headers already sent
```

I've seen the same error message in yii-web too.

**Comment by machour** [comment]
Seems like there was some changes in PHP 7.2:
https://github.com/php/php-src/commit/7f196e3#diff-7748eb3bfdd3bf962553f6f9f2723c45R39

**Comment by FabrizioCaldarelli** [comment]
Fixed https://github.com/yiisoft/yii-auth-client/pull/8
